import svgwrite
import os
from typing import Dict, List, Tuple

# Nepali abbreviations for planets
PLANET_ABBR_NEPALI = {
    'sun': 'सू', 'moon': 'च', 'mars': 'मं', 'mercury': 'बु',
    'jupiter': 'गु', 'venus': 'शु', 'saturn': 'श',
    'rahu': 'रा', 'ketu': 'के'
}

DEVANAGARI_DIGITS = {
    '0': '०', '1': '१', '2': '२', '3': '३', '4': '४',
    '5': '५', '6': '६', '7': '७', '8': '८', '9': '९'
}

def to_devanagari(number: int) -> str:
    return ''.join(DEVANAGARI_DIGITS[d] for d in str(number))

# Kundali diagram style colors
COLORS = {
    'bg': '#111111',
    'border': '#f39c12',
    'line': '#f39c12',
    'text_planet': '#ffffff',
    'text_sign': '#ffffff',
    'text_vakri': '#f39c12'
}

HOUSE_SIGN_POSITIONS = {
    1: (250, 90), 2: (160, 80), 3: (90, 150), 4: (110, 245),
    5: (90, 345), 6: (160, 455), 7: (250, 410), 8: (340, 455),
    9: (430, 345), 10: (410, 245), 11: (430, 150), 12: (340, 80)
}

HOUSE_PLANET_POSITIONS = {
    1: (250, 130), 2: (160, 105), 3: (90, 180), 4: (110, 280),
    5: (90, 380), 6: (160, 470), 7: (250, 430), 8: (340, 470),
    9: (430, 380), 10: (410, 280), 11: (430, 180), 12: (340, 105)
}

def generate_kundali_chart(data: Dict, output_path: str, is_navamsha: bool = False):
    """Generate North Indian Diamond Chart (Hamro Patro style)"""
    dwg = svgwrite.Drawing(output_path, size=(520, 520), profile='full')
    dwg.add(dwg.rect(insert=(0, 0), size=('100%', '100%'), fill=COLORS['bg']))
    dwg.add(dwg.rect(insert=(10, 10), size=(500, 500), fill='none', stroke=COLORS['border'], stroke_width=5, rx=20, ry=20))

    # Diamond grid
    lines = [
        ((10, 10), (510, 510)),
        ((10, 510), (510, 10)),
        ((10, 260), (260, 10)),
        ((260, 10), (510, 260)),
        ((510, 260), (260, 510)),
        ((260, 510), (10, 260))
    ]
    for start, end in lines:
        dwg.add(dwg.line(start=start, end=end, stroke=COLORS['line'], stroke_width=3, stroke_linecap='round'))

    if is_navamsha:
        planets_data = data['navamsha']['planets']
        start_raashi = data['navamsha']['ascendant']['raashi'] + 1
    else:
        planets_data = data['planets']
        start_raashi = data['ascendant']['raashi'] + 1

    house_planets = {i + 1: [] for i in range(12)}
    for p_name, p_info in planets_data.items():
        if is_navamsha:
            nav_p_r = p_info['raashi']
            nav_a_r = data['navamsha']['ascendant']['raashi']
            h = (nav_p_r - nav_a_r + 12) % 12 + 1
        else:
            h = data['planet_houses'][p_name]

        label = PLANET_ABBR_NEPALI[p_name]
        if not is_navamsha and p_info.get('is_vakri'):
            label += '(व)'
        house_planets[h].append(label)

    # Title label for chart type
    chart_label = 'नवमांश कुण्डली' if is_navamsha else 'जन्म कुण्डली'
    dwg.add(dwg.text(chart_label, insert=(260, 45), fill=COLORS['text_planet'],
                     font_size='24px', font_weight='700', text_anchor='middle'))

    # Render sign numbers in each house
    for house_number, (sx, sy) in HOUSE_SIGN_POSITIONS.items():
        sign_num = (start_raashi + house_number - 1 - 1) % 12 + 1
        dwg.add(dwg.text(to_devanagari(sign_num), insert=(sx, sy), fill=COLORS['text_sign'],
                         font_size='20px', font_weight='bold', text_anchor='middle'))

    # Render planets
    for h, labels in house_planets.items():
        px, py = HOUSE_PLANET_POSITIONS[h]
        for idx, p_label in enumerate(labels):
            offset_y = idx * 24
            dwg.add(dwg.text(p_label, insert=(px, py + offset_y), fill=COLORS['text_planet'],
                             font_size='22px', font_weight='700', text_anchor='middle'))

    # Watermark for version/debugging
    dwg.add(dwg.text('generated by app v2', insert=(500, 515), fill=COLORS['text_sign'],
                     font_size='10px', font_weight='normal', text_anchor='end', opacity=0.5))

    dwg.save()

def generate_kundali_text_report(data: Dict) -> str:
    """Fallback text report"""
    return "Refined Hamro Patro style report"